cognito:
  user-pool-id: ${COGNITO_USER_POOL_ID}
  client-id: ${COGNITO_CLIENT_ID}
  client-secret: ${COGNITO_CLIENT_SECRET}
  issuer: https://cognito-idp.eu-north-1.amazonaws.com/${COGNITO_USER_POOL_ID}
